## ======================================================================
## Pipeline for GPDB PL/R GPPKG
## ======================================================================

groups:
- name: GPDB6
  jobs:
    - build_r_centos7
    - build_r_centos6
    - plr_centos7_build
    - plr_centos6_build
    - plr_ubuntu18_build
    - plr_centos6_test
    - plr_centos7_test
    - plr_ubuntu18_test

resource_types:
- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:

# Image Resources

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'

- name: centos-gpdb-dev-7
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '7-gcc6.2-llvm3.7'

- name: ubuntu18-image
  type: docker-image
  source:
    repository: pivotaldata/ubuntu-gpdb-dev
    tag: '16.04'

# Github Source Codes

- name: gpdb_src
  type: git
  source:
    branch: 6X_STABLE
    uri: {{gpdb-git-remote}}

- name: plr_src
  type: git
  source:
    branch: gpdb6
    uri: https://github.com/greenplum-db/plr.git

# centos 7

- name: bin_gpdb_centos7
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos7/bin_gpdb.tar.gz

- name: bin_gpdb_centos6
  type: gcs
  source:
    bucket: ((gcs-bucket-intermediates))
    json_key: ((concourse-gcs-resources-service-account-key))
    versioned_file: 6X_STABLE/bin_gpdb_centos6/bin_gpdb.tar.gz

- name: bin_gpdb_ubuntu18
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    bucket: procedural-languages-concourse-gpdb-5x-stable
    region_name: {{aws-region}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: build/gpdb_6x/bin_gpdb_ubuntu16/bin_gpdb.tar.gz

- name: bin_r_centos7
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos7/gpdb6/r/bin_r_centos7.tar.gz

- name: bin_r_centos6
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos6/gpdb6/r/bin_r_centos6.tar.gz

- name: plr_gpdb_centos7_build
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos7/gpdb6/plr-devel.gppkg

- name: plr_gpdb_centos6_build
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-centos6/gpdb6/plr-devel.gppkg

- name: plr_gpdb_ubuntu18_build
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    versioned_file: plr/plr-ubuntu18/gpdb6/plr-devel.gppkg

- name: plr_gpdb_centos7_bin
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    regexp: plr/published/gpdb6/plr-rhel7.gppkg

- name: plr_gpdb_centos6_bin
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    regexp: plr/published/gpdb6/plr-rhel6.gppkg

- name: plr_gpdb_ubuntu18_bin
  type: gcs
  source:
    json_key: {{concourse-gcs-resources-service-account-key}}
    bucket: {{gcs-bucket-intermediates}}
    regexp: plr/published/gpdb6/plr-ubuntu18.gppkg

- name: xz
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: dependancy/xz-5.2.2.tar.gz

- name: zlib
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: dependancy/zlib-1.2.8.tar.gz

- name: bzip2
  type: s3
  source:
    bucket: {{pl-bucket-name}}
    region_name: {{aws-region}}
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    versioned_file: dependancy/bzip2-1.0.6.tar.gz

## jobs
## ======================================================================

jobs:

# Build R GPPKG

- name: build_r_centos7
  plan:
  - aggregate:
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos7
      trigger: true
    - get: centos-gpdb-dev-7
    - get: xz
    - get: zlib
    - get: bzip2
  - task: r_centos7_build
    file: plr_src/concourse/tasks/build_r.yml
    image: centos-gpdb-dev-7
    output_mapping:
      bin_r: bin_r_centos7
    params:
      OSVER: centos7
  - put: bin_r_centos7
    params:
      file: bin_r_centos7/bin_r_centos7.tar.gz

- name: build_r_centos6
  plan:
  - aggregate:
    - get: plr_src
      trigger: true
    - get: bin_gpdb_centos6
      trigger: true
    - get: centos-gpdb-dev-6
    - get: xz
    - get: zlib
    - get: bzip2
  - task: r_centos6_build
    file: plr_src/concourse/tasks/build_r.yml
    image: centos-gpdb-dev-6
    output_mapping:
      bin_r: bin_r_centos6
    params:
      OSVER: centos6
  - put: bin_r_centos6
    params:
      file: bin_r_centos6/bin_r_centos6.tar.gz

# Build PLR GPPKG
- name: plr_centos7_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
    - get: bin_r_centos7
      passed: [build_r_centos7]
      trigger: true
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-7
      input_mapping:
        bin_r: bin_r_centos7
      output_mapping:
        bin_plr: plr_gpdb_centos7_build
      params:
        OSVER: centos7
        BLDARCH: rhel7_x86_64
        GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos7_build
      params:
        file: plr_gpdb_centos7_build/plr-*.gppkg

- name: plr_centos6_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: gpdb_src
    - get: bin_r_centos6
      passed: [build_r_centos6]
      trigger: true
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.yml
      image: centos-gpdb-dev-6
      input_mapping:
        bin_r: bin_r_centos6
      output_mapping:
        bin_plr: plr_gpdb_centos6_build
      params:
        OSVER: centos6
        BLDARCH: rhel6_x86_64
        GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos6_build
      params:
        file: plr_gpdb_centos6_build/plr-*.gppkg

- name: plr_ubuntu18_build
  max_in_flight: 3
  plan:
  - aggregate:
    - get: ubuntu18-image
    - get: plr_src
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
    - get: gpdb_src
      trigger: true
  - aggregate:
    - task: Build_PLR
      file: plr_src/concourse/tasks/build_plr.ubuntu.yml
      image: ubuntu18-image
      output_mapping:
        bin_plr: plr_gpdb_ubuntu18_build
      params:
        OSVER: ubuntu18
        BLDARCH: ubuntu18_amd64
        GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_ubuntu18_build
      params:
        file: plr_gpdb_ubuntu18_build/plr-*.gppkg

# Test PL/R GPPKG

- name: plr_centos6_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-6
    - get: plr_src
    - get: bin_plr
      resource: plr_gpdb_centos6_build
      passed: [plr_centos6_build]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos6
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-6
    output_mapping:
      plr_gppkg: plr_gpdb_centos6_bin
    params:
      OSVER: centos6
      BLDARCH: rhel6_x86_64
      GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos6_bin
      params:
        file: plr_gpdb_centos6_bin/plr-*.gppkg

- name: plr_centos7_test
  plan:
  - aggregate:
    - get: centos-gpdb-dev-7
    - get: plr_src
    - get: bin_plr
      resource: plr_gpdb_centos7_build
      passed: [plr_centos7_build]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_centos7
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: centos-gpdb-dev-7
    output_mapping:
      plr_gppkg: plr_gpdb_centos7_bin
    params:
      OSVER: centos7
      BLDARCH: rhel7_x86_64
      GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_centos7_bin
      params:
        file: plr_gpdb_centos7_bin/plr-*.gppkg

- name: plr_ubuntu18_test
  plan:
  - aggregate:
    - get: ubuntu18-image
    - get: plr_src
    - get: bin_plr
      resource: plr_gpdb_ubuntu18_build
      passed: [plr_ubuntu18_build]
      trigger: true
    - get: bin_gpdb
      resource: bin_gpdb_ubuntu18
    - get: gpdb_src
  - task: Test_PLR
    file: plr_src/concourse/tasks/test_plr.yml
    image: ubuntu18-image
    output_mapping:
      plr_gppkg: plr_gpdb_ubuntu18_bin
    params:
      OSVER: ubuntu18
      BLDARCH: ubuntu18_amd64
      GPDBVER: gp6
  - aggregate:
    - put: plr_gpdb_ubuntu18_bin
      params:
        file: plr_gpdb_ubuntu18_bin/plr-*.gppkg

